[pytest]
markers =
    smoke # marker for smoke tests
    regression # marker for regression tests
    skip # marker for skip tests that should be skipped
    xfail # marker for tests that are expected to fail